apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  name: custom-metrics-apiserver
  namespace: custom-metrics-adapter
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: custom-metrics-apiserver
