# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-public
#   namespace: monitoring
#   labels:
#     app: prometheus
#     component: core
#   annotations:
#     prometheus.io/scrape: 'false'
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 9090
#   selector:
#     app: prometheus
#     component: core
