apiVersion: v1
kind: Service
metadata:
  name: grafana-public
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: grafana
    component: core
