apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    app: prometheus
    component: alertmanager
spec:
  clusterIP: None
  ports:
    - name: prometheus-alertmanager
      port: 9093
      protocol: TCP
  selector:
    app: prometheus
    component: alertmanager
  type: ClusterIP
