apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/path: '/metrics'
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus
    component: pushgateway
spec:
  clusterIP: None
  ports:
    - name: prometheus-pushgateway
      port: 9091
      protocol: TCP
  selector:
    app: prometheus
    component: pushgateway
  type: ClusterIP
