apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: graphite-mapping
  namespace: monitoring
data:
  graphite-mapping.conf: |
    stats.k8s.counter.kafka-mirror-maker-controller.testing.*.worker.rebalance.*.*
    name="worker_rebalance"
    controller="$1"
    metric_type="$2"
    metric="$3"
