apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-graphite-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: graphite-exporter
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-graphite-exporter
      labels:
        app: prometheus
        component: graphite-exporter
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: prometheus-graphite-exporter
        image: prom/graphite-exporter:master
        args:
          # - '--storage.tsdb.retention=12h'
        ports:
        - containerPort: 9109
