apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  namespace: monitoring
  name: prometheus-graphite-exporter-public
  labels:
    app: prometheus
    component: graphite-exporter-public
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9108
  selector:
    app: prometheus
    component: pushgateway
