apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: prometheus-graphite-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: graphite-exporter
spec:
  clusterIP: None
  ports:
    - name: prometheus-graphite-exporter
      port: 9108
      protocol: TCP
  selector:
    app: prometheus
    component: graphite-exporter
  type: ClusterIP
